# @package _global_
type: "color"
dataset: "Flowers102"
train:
  do: True
  epochs: 300
  batch_size: 64
  valid_every: 10
  weight_decay: 0
  lr: 1.0e-3
  lr_probs: 1.0e-4
  lamda: 0
  lamda2: 0
model:
  architecture: resnet18
  rot: 3
  partial: False
  variational: False
  version: "v1.0"
  vplayers: h1t1
  maxpool: True
  insta: False
  insta_params:
    num_samples: 1
    lambda_entropy: 1e-4
    h_min: -1.5
    h_max: 2
ada_aug:
  model_name: resnet18
  grad_clip: 5.0
  epochs: 200
  search_freq: 1
  search_ratio: 0.5