# @package _global_
type: "color"
dataset: "MNIST"
train:
  do: True
  epochs: 1500
  batch_size: 256
  valid_every: 10
  weight_decay: 1.0e-5
  lr: 1.0e-3
  lr_probs: 1.0e-4
  lamda: 0
  lamda2: 0
model:
  rot: 3
  partial: False
  variational: False
  version: "v1.0"
  insta: False
  insta_params:
    num_samples: 1
    lambda_entropy: 1.0e-4
    h_min: -1.5
    h_max: 2